FROM oven/bun:1

WORKDIR /user/src/app

COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./packages ./packages
COPY ./apps/web ./apps/web

RUN bun install
RUN bun run db:migrate
RUN bun run build

EXPOSE 3000

CMD ["bun","run","start:web"]