name: Deploy WS
on:
    push:
        branches: [main]
jobs:
    build-image:
        name: Build Docker Images
        runs-on: Ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push to dockerhub
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.ws
                push: true
                tags: arjunambavane/todo-stack-ws:${{ github.sha }}

            - name: Deploy to VM
              run: | 
                    echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
                    chmod 700 /home/runner/ssh_key
                    ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@139.59.18.154 -t "docker stop user_ws && docker run --name user_ws -d -p 8080:8080 arjunambavane/todo-stack-ws:${{ github.sha }}"      